name = "LogicalQueryProtocol"
uuid = "a92373ee-6cc4-4662-ae66-0c99a03ebae1"
version = "0.3.0"
authors = ["RelationalAI"]

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
Aqua = "= 0.8.14"
ExplicitImports = "= 1.14.2"
JET = "0.9, 0.10, 0.11"
JuliaInterpreter = "0.9, 0.10"
ProtoBuf = "1.2.0"
ReTestItems = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ExplicitImports", "JET", "JuliaInterpreter", "Logging", "ReTestItems", "Test"]
