name = "LogicalQueryProtocol"
uuid = "a92373ee-6cc4-4662-ae66-0c99a03ebae1"
version = "0.1.0"
authors = ["RelationalAI"]

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
ProtoBuf = "1.2.0"
ReTestItems = "1.35.1"
julia = "1.6"

[extras]
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ReTestItems", "Test"]
